### ISSUE TITLE
Working files not persisted

### ISSUE THREAD

**Issue by leeahoward** [player-two/brackets-vim#7]
When reloading a project the working file set is not persisted when I have this plugin installed.

I also noticed that if I use :e to open a file it does get persisted, but only the last file opened seems to stick.

**Comment by player-two** [comment]
Hello @leeahoward,

Actually, this is the intended function of the plugin.  In the File Operations section of the readme, you will note an emphasis on using the provided file opening commands.  Without going into too much detail (you can look through the code if you want more), the plugin manages the working file set in order to enable the hackish splitting feature that it implements.  When the splitview branch of Brackets is merged into master, I will refactor the plugin to use the new api, and your issue should disappear entirely.

I'm going to close this one unless you have any follow-up concerns.  You can follow issue #4 for updates on the splitview stuff.
